name: Build and Push Docker Image

# Триггеры для workflow
on:
  push:
    branches:
      - main # Workflow запускается на push в ветку main
  pull_request:
    branches:
      - main # Также запускается при PR в main

# Описание выполняемых задач
# Описание задач
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Проверка кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Установка Docker (если необходимо)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Сборка Docker-образа
      - name: Build Docker Image
        run: |
          docker build -t you_front:latest .

      # 4. Запуск контейнера для тестирования (опционально)
      - name: Run Container For Validation
        run: |
          docker run --rm you_front:latest echo "Container works fine!"
